In [1]:
import pandas as pd

In [8]:
l = range(1, 6)

In [9]:
index = ["a", "b", "c", "d", "e"]

In [10]:
arr = pd.Series(l, index)

In [11]:
print(arr)

a    1
b    2
c    3
d    4
e    5
dtype: int64


In [7]:
print("index {}: {}".format(3, arr[3]))

index 3: 4


In [9]:
area_category = pd.read_csv('area_category.csv')
area_map = pd.read_csv('area_map.csv')
area_struct = pd.read_csv('area_struct.csv')

In [12]:
d = {'a': 1, 'b': 2, 'c': 3}

In [13]:
ds = pd.Series(d)

In [16]:
ds

a    1
b    2
c    3
dtype: int64

In [17]:
print(ds)

a    1
b    2
c    3
dtype: int64


In [27]:
l = [num for num in range(1, 6)]

In [28]:
d = "abcde"

In [33]:
x=dict(zip(d, l))

In [34]:
print(x)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}


In [35]:
s = pd.Series(range(1, 20))

In [38]:
s[[1, 5]]

1    2
5    6
dtype: int64

In [39]:
s = pd.Series(range(1, 20))

In [40]:
s

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
dtype: int64

In [41]:
s[s % 2 == 0]

1      2
3      4
5      6
7      8
9     10
11    12
13    14
15    16
17    18
dtype: int64

In [42]:
s[s > 2]

2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
dtype: int64

In [44]:
s[s> s.mean()]

10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
dtype: int64

In [45]:
print('{}'.format(s.values))

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [51]:
print('{}'.format(s.keys))

<bound method Series.keys of 0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
dtype: int64>


In [52]:
s = pd.Series(range(1, 20))

In [53]:
s *= 2

In [54]:
s

0      2
1      4
2      6
3      8
4     10
5     12
6     14
7     16
8     18
9     20
10    22
11    24
12    26
13    28
14    30
15    32
16    34
17    36
18    38
dtype: int64

In [55]:
s = s + s + s

In [56]:
s

0       6
1      12
2      18
3      24
4      30
5      36
6      42
7      48
8      54
9      60
10     66
11     72
12     78
13     84
14     90
15     96
16    102
17    108
18    114
dtype: int64

In [57]:
np.sin(s)

NameError: name 'np' is not defined

In [58]:
import numpy as np

In [59]:
np.sin(s)

0    -0.279415
1    -0.536573
2    -0.750987
3    -0.905578
4    -0.988032
5    -0.991779
6    -0.916522
7    -0.768255
8    -0.558789
9    -0.304811
10   -0.026551
11    0.253823
12    0.513978
13    0.733190
14    0.893997
15    0.983588
16    0.994827
17    0.926819
18    0.784980
dtype: float64

In [7]:
import numpy as np

In [8]:
from numpy import random

In [21]:
help(random.rand())

Help on float object:

class float(object)
 |  float(x=0, /)
 |
 |  Convert a string or number to a floating-point number, if possible.
 |
 |  Methods defined here:
 |
 |  __abs__(self, /)
 |      abs(self)
 |
 |  __add__(self, value, /)
 |      Return self+value.
 |
 |  __bool__(self, /)
 |      True if self else False
 |
 |  __ceil__(self, /)
 |      Return the ceiling as an Integral.
 |
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |
 |  __eq__(self, value, /)
 |      Return self==value.
 |
 |  __float__(self, /)
 |      float(self)
 |
 |  __floor__(self, /)
 |      Return the floor as an Integral.
 |
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |
 |  __format__(self, format_spec, /)
 |      Formats the float according to format_spec.
 |
 |  __ge__(self, value, /)
 |      Return self>=value.
 |
 |  __getnewargs__(self, /)
 |
 |  __gt__(self, value, /)
 |      Return self>value.
 |
 |  __hash__(self, /)
 |      Return hash(self).
 |
 |  __int__(

In [35]:
type(random.choice(['a', 'b']))

numpy.str_

In [52]:
arr1 = np.array(random.randint(10, size=10))
arr2 = np.array(random.randint(10, size=10))

In [53]:
arr1

array([9, 2, 7, 4, 4, 5, 2, 9, 2, 8], dtype=int32)

In [54]:
arr2

array([6, 3, 8, 0, 5, 4, 2, 2, 7, 6], dtype=int32)

In [56]:
print(arr1 + arr2)

[15  5 15  4  9  9  4 11  9 14]


--- 1. 실제 파일 데이터 불러오기 및 내용 확인 ---

[area_map.csv 내용]
      x   y  ConstructionSite
0     1   1                 0
1     1   2                 0
2     1   3                 0
3     1   4                 0
4     1   5                 0
..   ..  ..               ...
220  15  11                 0
221  15  12                 0
222  15  13                 0
223  15  14                 0
224  15  15                 0

[225 rows x 3 columns]

[area_struct.csv 내용]
      x   y  category  area
0     1   1         0     0
1     1   2         0     0
2     1   3         0     0
3     1   4         2     0
4     1   5         0     0
..   ..  ..       ...   ...
220  15  11         0     3
221  15  12         0     3
222  15  13         0     3
223  15  14         0     3
224  15  15         0     3

[225 rows x 4 columns]

[area_category.csv 내용]
   category            struct
0         1         Apartment
1         2          Building
2         3            MyHome
3         4   BandalgomCoffee


데이터 처

In [59]:
area_map_df = pd.read_csv('area_map.csv')
area_struct_df = pd.read_csv('area_struct.csv')
area_category_df = pd.read_csv('area_category.csv')

In [60]:
area_category_df

category            struct
0         1         Apartment
1         2          Building
2         3            MyHome
3         4   BandalgomCoffee

In [61]:
area_map_df

x   y  ConstructionSite
0     1   1                 0
1     1   2                 0
2     1   3                 0
3     1   4                 0
4     1   5                 0
..   ..  ..               ...
220  15  11                 0
221  15  12                 0
222  15  13                 0
223  15  14                 0
224  15  15                 0

[225 rows x 3 columns]

In [62]:
area_struct_df

x   y  category  area
0     1   1         0     0
1     1   2         0     0
2     1   3         0     0
3     1   4         2     0
4     1   5         0     0
..   ..  ..       ...   ...
220  15  11         0     3
221  15  12         0     3
222  15  13         0     3
223  15  14         0     3
224  15  15         0     3

[225 rows x 4 columns]

In [63]:
import pandas as pd

# 1. CSV 파일들을 데이터프레임으로 불러옵니다.
area_category_df = pd.read_csv('area_category.csv')
area_map_df = pd.read_csv('area_map.csv')
area_struct_df = pd.read_csv('area_struct.csv')

In [64]:
# 2. 'area_category.csv' 파일의 ' struct' 열 이름에서 앞쪽 공백을 제거합니다.
area_category_df.rename(columns={' struct': 'struct'}, inplace=True)

In [ ]:
# 3. 'area_map_df'와 'area_struct_df'를 'x'와 'y'를 기준으로 병합합니다.
merged_map_struct_df = pd.merge(area_map_df, area_struct_df, on=['x', 'y'])

In [71]:
final_df = pd.merge(merged_map_struct_df, area_category_df, on='category', how='left')

In [72]:
print(final_df)

      x   y  ConstructionSite  category  area     struct
0     1   1                 0         0     0        NaN
1     1   2                 0         0     0        NaN
2     1   3                 0         0     0        NaN
3     1   4                 0         2     0   Building
4     1   5                 0         0     0        NaN
..   ..  ..               ...       ...   ...        ...
220  15  11                 0         0     3        NaN
221  15  12                 0         0     3        NaN
222  15  13                 0         0     3        NaN
223  15  14                 0         0     3        NaN
224  15  15                 0         0     3        NaN

[225 rows x 6 columns]


In [73]:
final_df_sorted = final_df.sort_values(by='area')

In [ ]:
final_df_sorted

In [75]:
# 2. (핵심) 'area' 열의 값이 1인 데이터만 필터링합니다.
area_1_data = final_df_sorted[final_df_sorted['area'] == 1]

# 3. 필터링된 결과를 출력합니다.
print("area가 1인 데이터:")
print(area_1_data)

area가 1인 데이터:
     x   y  ConstructionSite  category  area            struct
28   2  14                 0         1     1         Apartment
26   2  12                 0         4     1   BandalgomCoffee
29   2  15                 0         0     1               NaN
25   2  11                 0         0     1               NaN
24   2  10                 0         0     1               NaN
22   2   8                 1         0     1               NaN
27   2  13                 0         0     1               NaN
7    1   8                 0         0     1               NaN
8    1   9                 0         0     1               NaN
10   1  11                 0         0     1               NaN
9    1  10                 0         0     1               NaN
11   1  12                 0         0     1               NaN
12   1  13                 0         1     1         Apartment
13   1  14                 0         2     1          Building
23   2   9                 1         0   

x   y  ConstructionSite  category  area     struct
0     1   1                 0         0     0        NaN
1     1   2                 0         0     0        NaN
2     1   3                 0         0     0        NaN
3     1   4                 0         2     0   Building
4     1   5                 0         0     0        NaN
..   ..  ..               ...       ...   ...        ...
220  15  11                 0         0     3        NaN
221  15  12                 0         0     3        NaN
222  15  13                 0         0     3        NaN
223  15  14                 0         0     3        NaN
224  15  15                 0         0     3        NaN

[225 rows x 6 columns]

In [67]:
print(area_map_df)

      x   y  ConstructionSite
0     1   1                 0
1     1   2                 0
2     1   3                 0
3     1   4                 0
4     1   5                 0
..   ..  ..               ...
220  15  11                 0
221  15  12                 0
222  15  13                 0
223  15  14                 0
224  15  15                 0

[225 rows x 3 columns]


In [68]:
print(area_struct_df)

      x   y  category  area
0     1   1         0     0
1     1   2         0     0
2     1   3         0     0
3     1   4         2     0
4     1   5         0     0
..   ..  ..       ...   ...
220  15  11         0     3
221  15  12         0     3
222  15  13         0     3
223  15  14         0     3
224  15  15         0     3

[225 rows x 4 columns]


In [ ]:
print(merged_map_struct_df)

In [69]:
print(area_category_df)


   category            struct
0         1         Apartment
1         2          Building
2         3            MyHome
3         4   BandalgomCoffee


In [ ]:

# 4. 위에서 병합된 데이터프레임과 'area_category_df'를 'category'를 기준으로 병합합니다.
#    (left join을 사용하여 'merged_map_struct_df'의 모든 데이터를 유지합니다.)
final_df = pd.merge(merged_map_struct_df, area_category_df, on='category', how='left')

In [ ]:

# 5. 최종 데이터프레임을 'area' 열을 기준으로 오름차순 정렬합니다.
final_df_sorted = final_df.sort_values(by='area')

In [ ]:

# 6. 결과를 새로운 CSV 파일로 저장합니다.
final_df_sorted.to_csv('merged_and_sorted_area_data.csv', index=False)

In [ ]:

# 7. 병합 및 정렬된 데이터프레임의 첫 5개 행을 출력하여 확인합니다.
print("병합 및 정렬된 데이터프레임:")
print(final_df_sorted.head())